// Generated by CoffeeScript 1.8.0
(function() {
  var api, exp, express, _port;

  _port = 8999;

  express = require("express");

  exp = express();

  exp.configure(function() {
    exp.use(express.bodyParser());
    exp.use(express.methodOverride());
    exp.use(exp.router);
  });

  api = require("./../api/api.js");

  exp.post("/api/docs/image/create", api.addImage);

  exp["delete"]("/api/docs/image/delete/:prodId/:id", api.deleteProdImage);

  exp.get("/api/docs/image/:id", api.getFullSizeImage);

  exp.post("/api/product/create", api.addProd);

  exp.post("/api/product/edit", api.updateProd);

  exp["delete"]("/api/product/delete/:id", api.deleteProd);

  exp.get("/api/product/item/:id", api.getProd);

  exp.get("/api/product/items", api.getProdList);

  exp.listen(_port);

  console.log("The applistion's listening on port# " + _port);

  process.on("uncaughtException", function(err) {
    console.log("Application exits. err: " + err);
  });

  process.on("SIGTERM", function(err) {
    console.log("Application killed successfully. err: " + err);
  });

  module.exports = exp;

}).call(this);
