// Generated by CoffeeScript 1.8.0
(function() {
  exports.exec = function(cmd, cb) {
    var child_process, p, parts;
    child_process = require("child_process");
    parts = cmd.split(/\s+/g);
    p = child_process.spawn(parts[0], parts.slice(1), {
      stdio: "inherit"
    });
    p.on("exit", function(code) {
      var err;
      err = null;
      if (code) {
        err = new Error("command \"" + cmd + "\" exited with wrong status code \"" + code + "\"");
        err.code = code;
        err.cmd = cmd;
      }
      cb && cb(err);
    });
  };

  exports.series = function(cmds, cb) {
    var execNext;
    execNext = function() {
      exports.exec(cmds.shift(), function(err) {
        if (err) {
          cb(err);
        } else {
          if (cmds.length) {
            execNext();
          } else {
            cb(null);
          }
        }
      });
    };
    execNext();
  };

}).call(this);
