// Generated by CoffeeScript 1.8.0
(function() {
  var ObjectId, Schema, mongoose, prodSchema;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  prodSchema = new Schema({
    name: String,
    code: String,
    sizes: [String],
    desc: String,
    images: Schema.Types.Mixed,
    date: {
      type: Date,
      "default": Date.now
    }
  });

  module.exports = prodSchema;

}).call(this);
